/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as UmrahRouteImport } from './routes/umrah'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FlightsRouteImport } from './routes/flights'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingSuccessRouteImport } from './routes/booking-success'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PackagesSlugRouteImport } from './routes/packages.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminFlightRequestsRouteImport } from './routes/admin.flight-requests'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminBranchesRouteImport } from './routes/admin.branches'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdminPackagesIndexRouteImport } from './routes/admin.packages.index'
import { Route as AdminPackagesIdRouteImport } from './routes/admin.packages.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrahRoute = UmrahRouteImport.update({
  id: '/umrah',
  path: '/umrah',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightsRoute = FlightsRouteImport.update({
  id: '/flights',
  path: '/flights',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSuccessRoute = BookingSuccessRouteImport.update({
  id: '/booking-success',
  path: '/booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PackagesSlugRoute = PackagesSlugRouteImport.update({
  id: '/packages/$slug',
  path: '/packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFlightRequestsRoute = AdminFlightRequestsRouteImport.update({
  id: '/flight-requests',
  path: '/flight-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBranchesRoute = AdminBranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPackagesIndexRoute = AdminPackagesIndexRouteImport.update({
  id: '/packages/',
  path: '/packages/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPackagesIdRoute = AdminPackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => AdminRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/booking-success': typeof BookingSuccessRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/flights': typeof FlightsRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trips': typeof TripsRoute
  '/umrah': typeof UmrahRoute
  '/visa': typeof VisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/flight-requests': typeof AdminFlightRequestsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/packages/$id': typeof AdminPackagesIdRoute
  '/admin/packages/': typeof AdminPackagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/booking-success': typeof BookingSuccessRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/flights': typeof FlightsRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trips': typeof TripsRoute
  '/umrah': typeof UmrahRoute
  '/visa': typeof VisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/flight-requests': typeof AdminFlightRequestsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/packages/$id': typeof AdminPackagesIdRoute
  '/admin/packages': typeof AdminPackagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/booking': typeof BookingRoute
  '/booking-success': typeof BookingSuccessRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/flights': typeof FlightsRoute
  '/gallery': typeof GalleryRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/trips': typeof TripsRoute
  '/umrah': typeof UmrahRoute
  '/visa': typeof VisaRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/branches': typeof AdminBranchesRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/flight-requests': typeof AdminFlightRequestsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/packages/$slug': typeof PackagesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/packages/$id': typeof AdminPackagesIdRoute
  '/admin/packages/': typeof AdminPackagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/booking-success'
    | '/contact'
    | '/faq'
    | '/flights'
    | '/gallery'
    | '/mcp'
    | '/reset-password'
    | '/trips'
    | '/umrah'
    | '/visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/admins'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/faq'
    | '/admin/flight-requests'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/packages/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/packages/$id'
    | '/admin/packages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/booking-success'
    | '/contact'
    | '/faq'
    | '/flights'
    | '/gallery'
    | '/mcp'
    | '/reset-password'
    | '/trips'
    | '/umrah'
    | '/visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/admins'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/faq'
    | '/admin/flight-requests'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/packages/$slug'
    | '/admin'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/packages/$id'
    | '/admin/packages'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/booking'
    | '/booking-success'
    | '/contact'
    | '/faq'
    | '/flights'
    | '/gallery'
    | '/mcp'
    | '/reset-password'
    | '/trips'
    | '/umrah'
    | '/visa'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/admins'
    | '/admin/blog'
    | '/admin/bookings'
    | '/admin/branches'
    | '/admin/customers'
    | '/admin/faq'
    | '/admin/flight-requests'
    | '/admin/gallery'
    | '/admin/messages'
    | '/admin/notifications'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/blog/$slug'
    | '/legal/privacy'
    | '/legal/terms'
    | '/packages/$slug'
    | '/admin/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/packages/$id'
    | '/admin/packages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookingRoute: typeof BookingRoute
  BookingSuccessRoute: typeof BookingSuccessRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  FlightsRoute: typeof FlightsRoute
  GalleryRoute: typeof GalleryRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TripsRoute: typeof TripsRoute
  UmrahRoute: typeof UmrahRoute
  VisaRoute: typeof VisaRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PackagesSlugRoute: typeof PackagesSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umrah': {
      id: '/umrah'
      path: '/umrah'
      fullPath: '/umrah'
      preLoaderRoute: typeof UmrahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flights': {
      id: '/flights'
      path: '/flights'
      fullPath: '/flights'
      preLoaderRoute: typeof FlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-success': {
      id: '/booking-success'
      path: '/booking-success'
      fullPath: '/booking-success'
      preLoaderRoute: typeof BookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/packages/$slug': {
      id: '/packages/$slug'
      path: '/packages/$slug'
      fullPath: '/packages/$slug'
      preLoaderRoute: typeof PackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/flight-requests': {
      id: '/admin/flight-requests'
      path: '/flight-requests'
      fullPath: '/admin/flight-requests'
      preLoaderRoute: typeof AdminFlightRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/branches': {
      id: '/admin/branches'
      path: '/branches'
      fullPath: '/admin/branches'
      preLoaderRoute: typeof AdminBranchesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/packages/': {
      id: '/admin/packages/'
      path: '/packages'
      fullPath: '/admin/packages/'
      preLoaderRoute: typeof AdminPackagesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/packages/$id': {
      id: '/admin/packages/$id'
      path: '/packages/$id'
      fullPath: '/admin/packages/$id'
      preLoaderRoute: typeof AdminPackagesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBranchesRoute: typeof AdminBranchesRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminFlightRequestsRoute: typeof AdminFlightRequestsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPackagesIdRoute: typeof AdminPackagesIdRoute
  AdminPackagesIndexRoute: typeof AdminPackagesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBranchesRoute: AdminBranchesRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminFlightRequestsRoute: AdminFlightRequestsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPackagesIdRoute: AdminPackagesIdRoute,
  AdminPackagesIndexRoute: AdminPackagesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  BookingRoute: BookingRoute,
  BookingSuccessRoute: BookingSuccessRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  FlightsRoute: FlightsRoute,
  GalleryRoute: GalleryRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TripsRoute: TripsRoute,
  UmrahRoute: UmrahRoute,
  VisaRoute: VisaRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  PackagesSlugRoute: PackagesSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
