UPDATE public.gallery_items SET title_fr = m.fr FROM (VALUES
('الحرم المكي','La Grande Mosquée de La Mecque'),
('الكعبة المشرفة ليلاً','La Kaaba de nuit'),
('المسجد النبوي - المنارة','Mosquée du Prophète — le minaret'),
('المسجد النبوي','La Mosquée du Prophète'),
('باب بدر - المسجد النبوي','Porte de Badr — Mosquée du Prophète'),
('إسطنبول','Istanbul'),
('باب عمر بن الخطاب','Porte d''Omar Ibn Al-Khattab'),
('دبي','Dubaï'),
('ماليزيا','Malaisie'),
('أروقة المسجد النبوي','Les galeries de la Mosquée du Prophète'),
('باريس','Paris'),
('باب السلام','Porte de la Paix (Bab As-Salam)'),
('المدينة المنورة','Médine'),
('حجاجنا في ساحة المسجد النبوي','Nos pèlerins sur l''esplanade de la Mosquée du Prophète'),
('مقصورة الطائرة','Cabine de l''avion'),
('المعتمرون في الإحرام','Les pèlerins en état d''Ihram'),
('مجموعة المعتمرات','Groupe de pèlerines'),
('زيارة جبل أحد','Visite du mont Ouhoud'),
('الكعبة المشرفة وبرج الساعة ليلاً','La Kaaba et la tour de l''horloge de nuit'),
('وصول المعتمرات إلى مطار المدينة المنورة','Arrivée des pèlerines à l''aéroport de Médine'),
('مجموعة المعتمرات مع فريق جنة الصحراء','Groupe de pèlerines avec l''équipe Janat Sahara'),
('زيارة جبل أحد بالمدينة المنورة','Visite du mont Ouhoud à Médine'),
('المعتمرون داخل المسجد الحرام','Les pèlerins dans la Mosquée sacrée'),
('لحظات الدعاء داخل الحرم المكي','Moments de prière dans la Mosquée sacrée'),
('ساحة المسجد النبوي مع مجموعة الحجاج','Esplanade de la Mosquée du Prophète avec le groupe'),
('ليلة في ساحات المدينة المنورة','Une nuit sur les esplanades de Médine'),
('باب جبريل — المسجد النبوي','Porte de Gabriel — Mosquée du Prophète'),
('صورة جماعية أمام المسجد النبوي','Photo de groupe devant la Mosquée du Prophète')
) AS m(ar, fr)
WHERE public.gallery_items.title = m.ar;